# Q2

In [1]:
def l2_dist(a, b):
    result = ((a - b) * (a - b)).sum()
    result = result ** 0.5
    return result

In [2]:
import numpy as np
a = np.random.rand(20,20)
print(a)

b = np.random.rand(20,20)
print(b)

[[0.55905743 0.4488158  0.81098127 0.88282236 0.10714123 0.41292707
  0.46334395 0.89302687 0.18538945 0.54235675 0.699173   0.3999975
  0.64206032 0.62598711 0.91285379 0.47746954 0.5622156  0.12321536
  0.74869599 0.7756466 ]
 [0.35766607 0.94329375 0.22164411 0.07002145 0.34517146 0.06018251
  0.09830067 0.02987555 0.90267799 0.8317869  0.65648747 0.05892805
  0.86271395 0.83644268 0.80589058 0.71533344 0.86477175 0.29172032
  0.04530765 0.08450022]
 [0.48224421 0.12381648 0.03398026 0.80628584 0.44724761 0.80265245
  0.29276787 0.20462351 0.90338241 0.18611297 0.02806038 0.42037616
  0.23546384 0.09152882 0.74125187 0.32485527 0.69896525 0.95590125
  0.81381056 0.99410522]
 [0.74384919 0.02803511 0.67271628 0.72705232 0.71379032 0.83227937
  0.08597372 0.73218978 0.73788121 0.66221332 0.64640001 0.30089755
  0.0609256  0.72308497 0.63350236 0.80803431 0.92913716 0.96018228
  0.42940155 0.33495096]
 [0.19168611 0.74165306 0.47329279 0.38213974 0.27687873 0.59427225
  0.00563961 0.76

In [3]:
l2_dist(a, b)

8.411683714144164

In [4]:
l2_dist(a.T, b.T)

8.411683714144164

In [5]:
l2_dist(np.reshape(a, (20 * 20)), np.reshape(b, (20 * 20)))

8.411683714144164

In [6]:
l2_dist(np.reshape(a, (20 * 20)), np.reshape(b, (20 * 20, 1)))

162.24641039820685

# Q3

In [7]:
a1 = np.random.rand(4)
print(a1)

[0.32318996 0.118119   0.80010818 0.17874748]


In [8]:
a2 = np.random.rand(4, 1)
print(a2)

[[0.9398607 ]
 [0.80968739]
 [0.30298115]
 [0.70523283]]


In [9]:
a3 = np.array([[1, 2, 3, 4]])
print(a3)

[[1 2 3 4]]


In [10]:
a4 = np.arange(1, 4, 1)
print(a4)

[1 2 3]


In [11]:
a5 = np.linspace(1 ,4, 4)
print(a5)

[1. 2. 3. 4.]


In [12]:
a1.shape == a5.shape

True

# Q4

In [13]:
old = np.array([[1, 1, 1], [1, 1, 1]])
new = old
new[0, :2] = 0
print(old)

[[0 0 1]
 [1 1 1]]


# Q5

In [14]:
r = np.random.rand(6,6)
print(r)

[[0.0743207  0.62311207 0.02909847 0.47150834 0.77328579 0.00829327]
 [0.44478311 0.92093324 0.44260292 0.96016258 0.91987641 0.85015439]
 [0.32467585 0.87027811 0.67730081 0.28778182 0.61167045 0.39388307]
 [0.72405627 0.47199922 0.60354544 0.04542408 0.48461927 0.1484963 ]
 [0.92525153 0.92714469 0.92363704 0.79287871 0.22775107 0.12506557]
 [0.45615166 0.35889185 0.21492906 0.53319865 0.92096861 0.76148804]]


In [15]:
r[2:4, 2:4]

array([[0.67730081, 0.28778182],
       [0.60354544, 0.04542408]])