# Q2

In [3]:
def l2_dist(a, b):
    result = ((a - b) * (a - b)).sum()
    result = result ** 0.5
    return result

In [14]:
import numpy as np
a = np.random.rand(20,20)
print(a)

b = np.random.rand(20,20)
print(b)

array([[2.80676884e-01, 6.81236318e-01, 3.42153719e-01, 7.58970764e-01,
        9.16367992e-01, 5.22149263e-01, 5.19142592e-01, 2.93452305e-02,
        7.87383653e-01, 8.33137839e-01, 4.28702434e-01, 2.25626091e-01,
        6.52304866e-01, 6.91536926e-01, 7.26311279e-01, 1.34299100e-01,
        1.18274817e-01, 5.81563549e-01, 1.84028713e-01, 3.41515987e-01],
       [8.34403461e-02, 2.80471194e-01, 3.08785735e-01, 7.48005347e-01,
        4.44346534e-01, 1.50925391e-01, 9.77839363e-01, 7.59596144e-01,
        9.38245717e-01, 9.06897817e-01, 1.80558000e-01, 5.27664086e-01,
        6.98636761e-01, 4.04183755e-01, 9.43546135e-01, 6.66548830e-01,
        5.69873929e-01, 7.04433164e-01, 5.12207983e-01, 3.83863362e-01],
       [8.71185540e-01, 3.09277280e-01, 6.97217561e-01, 1.87552506e-01,
        5.93376008e-01, 7.81999288e-01, 1.28620775e-01, 5.46932109e-01,
        5.88679069e-01, 1.24890021e-01, 8.25952688e-01, 2.11761350e-01,
        2.59179132e-01, 1.90321842e-01, 8.32792212e-01, 6.0839

In [9]:
l2_dist(a, b)

8.15476748799943

In [10]:
l2_dist(a.T, b.T)

8.15476748799943

In [11]:
l2_dist(np.reshape(a, (20 * 20)), np.reshape(b, (20 * 20)))

8.15476748799943

In [12]:
l2_dist(np.reshape(a, (20 * 20)), np.reshape(b, (20 * 20, 1)))

166.3795151761852

# Q3

In [16]:
a1 = np.random.rand(4)
print(a1)

array([0.5754574 , 0.94171732, 0.54712742, 0.59649657])

In [17]:
a2 = np.random.rand(4, 1)
print(a2)

array([[0.08132785],
       [0.15431048],
       [0.84307419],
       [0.55795435]])

In [18]:
a3 = np.array([[1, 2, 3, 4]])
print(a3)

array([[1, 2, 3, 4]])

In [19]:
a4 = np.arange(1, 4, 1)
print(a4)

array([1, 2, 3])

In [20]:
a5 = np.linspace(1 ,4, 4)
print(a5)

array([1., 2., 3., 4.])

In [21]:
a1.shape == a5.shape

True

# Q4

In [22]:
old = np.array([[1, 1, 1], [1, 1, 1]])
new = old
new[0, :2] = 0
print(old)

[[0 0 1]
 [1 1 1]]


# Q5

In [25]:
r = np.random.rand(6,6)
print(r)

array([[0.17528762, 0.63436596, 0.69841689, 0.34374109, 0.23499748,
        0.65466609],
       [0.61350384, 0.04965969, 0.75517225, 0.84473296, 0.25790168,
        0.66856544],
       [0.6431834 , 0.02721706, 0.41248979, 0.69652884, 0.94812861,
        0.15400603],
       [0.34765333, 0.84358408, 0.98206813, 0.81332746, 0.15926723,
        0.00359263],
       [0.59005521, 0.77389972, 0.08119583, 0.38704885, 0.79509339,
        0.440327  ],
       [0.93711833, 0.65903942, 0.70611133, 0.7439164 , 0.93188577,
        0.72009246]])

In [26]:
r[2:4, 2:4]

array([[0.41248979, 0.69652884],
       [0.98206813, 0.81332746]])